default.yml
Based on the [docs](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RegexpLiteral) for this rule, we misunderstood what `mixed` was meant to do.
I don't think there is a good way to keep this rule enabled, so we will just have to rely on developer discretion.
=> Style/RegexpLiteral: set Enabled: false

default.yml
It doesn't make sense for rubocop to inspect this file since we just check in the auto-generated version.
=> AllCops Exclude: db/schema.rb (as a generated file)

Gemfile.lock, ramsey_cop.gemspec
https://github.com/bbatsov/rubocop/releases/tag/v0.53.0
Follow Rubocop Latest Release
=> PLAT-1379 RuboCop 0.53.0 has been released

Gemfile.lock, ramsey_cop.gemspec
@jwsloan I'd like to slide one more bump in and then get that 0.8.0 out.
Release Notes for 0.54.0 https://github.com/bbatsov/rubocop/releases/tag/v0.54.0
Most interesting bit
[#5597](https://github.com/bbatsov/rubocop/pull/5597): Add new Rails/HttpStatus cop. I like this 👍
=> Bump rubocop dependency to 0.54.0

default.yml
I want to be able to have arbitrarily large `namespace` blocks.
=> Metrics/BlockLength: Exclude rake files

default.yml
These changes encompass the global overrides that have recently been accepted as part of a recent cleanup in FPU: https://github.com/lampo/fpu-online/pull/1440. We realize that these changes could be nice for other teams/repos as well, so we're recommending them for consideration here.
While we normally don't spend time on style-only changes, the FPU team has recently added automated code quality enforcement to remove the pain point of manual enforcement during code reviews.
I wanted to make sure we had a good understanding of how much this change would affect us in adjusting our programming habits, so I worked through all of the offenses in our repo. In addition to the easy automatic corrections, I corrected most of the offenses, silenced a few pieces of dense "legacy" code (in place to …
=> suggested changes from fpu-online

Gemfile.lock, lib/ramsey_cop/version.rb
Release support for rubocop 0.60.0
https://github.com/rubocop-hq/rubocop/releases/tag/v0.60.0
A team member reported local dev issues in VS Code with rubocop 0.59.2. This may or may not help, but we might as well attempt to stay current.
=> Release ramsey_cop 0.12.0

Gemfile.lock, lib/ramsey_cop/version.rb, ramsey_cop.gemspec
rubocop < 0.61 does not play well with Ruby 2.6. We need to expand to
accept that version.
Let's update everything else while we're at it.
With that done, we'll bump the version of RamseyCop as well.
=> chore: Update dependencies

Gemfile.lock, lib/ramsey_cop/version.rb, ramsey_cop.gemspec
We found a potential security vulnerability in a repository for which
you have been granted security alert access.
@RamseyInHouse  RamseyInHouse/ramsey-cop
Known low severity security vulnerability detected in rubocop < 0.48.1
defined in ramsey_cop.gemspec.
ramsey_cop.gemspec update suggested: rubocop ~> 0.49.0.
Always verify the validity and compatibility of suggestions with your
codebase.
=> fix: Update rubocop dependecy

Gemfile.lock, lib/ramsey_cop/version.rb, ramsey_cop.gemspec
The previous commit changed the rubocop lock from a nonexistent `~> 0` to a much more restrictive `~> 0.62.0`. This change will allow for future < 1.0 rubocop updates.
I pointed smartdollar-app to my local repo, updated rubocop to 0.66, and ran it to verify it was still complaining about older code as expected.
=> Relax rubocop

default.yml, lib/ramsey_cop/version.rb
Rubocop should not parse anything in the node_modules folder.
=> Ignore node_modules folder

default.yml
when running rubocop, it emits: `Warning: no department given for Documentation.`
The actual cop is not `Documentation` but `Style/Documentation`
=> Fix Documentation warning

Gemfile.lock, default.yml, lib/ramsey_cop/version.rb
This change enables the Style/Hash* cops added with Rubocop 0.80.
The big question is: are these new defaults acceptable to Ramsey senior devs, or do you have a case for another deviation from Rubocop's default style guide?
_n/a_
I've enabled these new cops in a couple of my own (i.e. non-Ramsey) repos and don't have any complaints.
=> Enable new Style/Hash* cops

Gemfile.lock, default.yml, lib/ramsey_cop/version.rb, ramsey_cop.gemspec
This change enables the new Lint cops added with Rubocop 0.81.
This also assumes the defaults are the desired approach for the codeowners of this repo.  Please let me know if one of them should not be enabled or something else set differently.
n/a
I enabled this in a few of my own repos and had no issues.
(e.g. bug fix, new feature, breaking change, etc.)
Enabled new cops due to the new version of Rubocop per the recommendation of [their documentation here](https://docs.rubocop.org/en/latest/versioning/).
=> Enable new Lint cops

Gemfile.lock, default.yml, lib/ramsey_cop/version.rb, ramsey_cop.gemspec
Bump version and add definitions for new non-default cops
=> Bump rubocop from 0.81.0 to 0.82.0

default.yml
In general, I think grouping similar macros is a good idea, and having spaces between most macros and methods makes sense.
[Source documentation](https://docs.rubocop.org/en/stable/cops_layout/#layoutemptylinesaroundattributeaccessor)
```ruby
attr_accessor :foo
def do_something
end
attr_accessor :foo
def do_something
end
attr_accessor :foo
attr_reader :bar
attr_writer :baz
attr :qux
def do_something
end
```
=> Layout/EmptyLinesAroundAttributeAccessor: Enabled: true

default.yml
Yeah, I find it very hard to read with spaces. Wouldn't have thought this needed a rule, but better to be explicit
[Source Documentation](https://docs.rubocop.org/en/stable/cops_layout/#layoutspacearoundmethodcalloperator)
```ruby
foo. bar
foo .bar
foo . bar
foo. bar .buzz
foo
. bar
. buzz
foo&. bar
foo &.bar
foo &. bar
foo &. bar&. buzz
RuboCop:: Cop
RuboCop:: Cop:: Cop
:: RuboCop::Cop
foo.bar
foo.bar.buzz
foo
.bar
.buzz
foo&.bar
foo&.bar&.buzz
RuboCop::Cop
RuboCop::Cop::Cop
::RuboCop::Cop
```
=> Layout/SpaceAroundMethodCallOperator: Enabled: true

default.yml
This makes sense to me, but I am curious to see what others think. I basically never use these literals.
[Source Documentation](https://docs.rubocop.org/en/latest/cops_style/#styleexponentialnotation)
```ruby
10e6
0.3e4
11.7e5
3.14e0
1e7
3e3
1.17e6
3.14
```
=> Style/ExponentialNotation: Enabled: true

default.yml
This is nice in that it trains people to use the new endless range feature I guess, but breaking that muscle memory will be hard.
[Source documentation](https://docs.rubocop.org/en/latest/cops_style/#styleslicingwithrange)
```ruby
items[1..-1]
items[1..]
```
=> Style/SlicingWithRange: Enabled: true

Gemfile.lock, default.yml, lib/ramsey_cop/version.rb, spec/ramsey_cop_spec.rb
* Adding a default for `NewCops`
* Adding a test for checking the validity of the `default.yml` file
This effectively fixes the warning when NewCops are added:
https://rubocop.readthedocs.io/en/latest/versioning/#pending-cops
Setting it to "disable" is probably the least disruptive, but if we want to set it to `enable` I'm ok with that too.  I mainly want it set to suppress the warning.
Take a look at the above doc link.  I believe that when a `cop` moves beyond the `new` status, rubocop will set the default one way or the other, then the `NewCop` setting no longer applies.  I think of this as... set it to `enabled` if you want to be on the bleeding edge of new cops, `disabled` if not.
(e.g. bug fix, new feature, breaking change, etc.)
=> Set default for NewCops
